name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "jk-backend-d1"
database_id = "050c0d78-33ff-405d-9c46-6e998cac8801"

[version_metadata]
binding = "CF_VERSION_METADATA"
